import Head from 'next/head'
import Link from 'next/link'

import colors from '../Data/colors.json'

export default function Home() {
  return (
    <div>
      <Head>
        <title>colors</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {colors.map(color => (
        <Link href={`/${color.name}`}>
          <h2>{color.name}</h2>
        </Link>
      ))}
          </div>
  )
}
